// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NewsServices.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace NewsMicroservice {
  public static partial class NewsGrpcService
  {
    static readonly string __ServiceName = "NewsGrpcService";

    static readonly grpc::Marshaller<global::NewsMicroservice.GetNewsRequest> __Marshaller_GetNewsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NewsMicroservice.GetNewsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NewsMicroservice.GetNewsResponse> __Marshaller_GetNewsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NewsMicroservice.GetNewsResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::NewsMicroservice.GetNewsRequest, global::NewsMicroservice.GetNewsResponse> __Method_GetNews = new grpc::Method<global::NewsMicroservice.GetNewsRequest, global::NewsMicroservice.GetNewsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetNews",
        __Marshaller_GetNewsRequest,
        __Marshaller_GetNewsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NewsMicroservice.NewsServicesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for NewsGrpcService</summary>
    public partial class NewsGrpcServiceClient : grpc::ClientBase<NewsGrpcServiceClient>
    {
      /// <summary>Creates a new client for NewsGrpcService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public NewsGrpcServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for NewsGrpcService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public NewsGrpcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected NewsGrpcServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected NewsGrpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::NewsMicroservice.GetNewsResponse GetNews(global::NewsMicroservice.GetNewsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetNews(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NewsMicroservice.GetNewsResponse GetNews(global::NewsMicroservice.GetNewsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetNews, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NewsMicroservice.GetNewsResponse> GetNewsAsync(global::NewsMicroservice.GetNewsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetNewsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NewsMicroservice.GetNewsResponse> GetNewsAsync(global::NewsMicroservice.GetNewsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetNews, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override NewsGrpcServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new NewsGrpcServiceClient(configuration);
      }
    }

  }
}
#endregion
